---
- name: DistributedComputeHCI
  ServicesDefault:
    - OS::TripleO::Services::Aide
    - OS::TripleO::Services::CephClient
    - OS::TripleO::Services::CephExternal
    - OS::TripleO::Services::CephGrafana
    - OS::TripleO::Services::CephMds
    - OS::TripleO::Services::CephMgr
    - OS::TripleO::Services::CephMon
    - OS::TripleO::Services::CephRbdMirror
    - OS::TripleO::Services::CephRgw
    - OS::TripleO::Services::CephOSD
    - OS::TripleO::Services::CinderVolumeEdge
    - OS::TripleO::Services::GlanceApiEdge
- name: DistributedComputeHCIScaleOut
  ServicesDefault:
    - OS::TripleO::Services::Aide
    - OS::TripleO::Services::CephClient
    - OS::TripleO::Services::CephExternal
    - OS::TripleO::Services::CephOSD
    - OS::TripleO::Services::HAproxyEdge
- name: DistributedComputeScaleOut
  ServicesDefault:
    - OS::TripleO::Services::Aide
    - OS::TripleO::Services::CephClient
    - OS::TripleO::Services::CephExternal
    - OS::TripleO::Services::HAproxyEdge
