---
- name: Ensure output dirs
  file:
    path: "{{ ansible_user_dir }}/zuul-output/logs"
    state: directory

- name: Directories needing root
  become: true
  block:
    - name: Ensure ci directories
      file:
        path: "/etc/ci"
        state: "directory"

    - name: Ensure ci mirror file
      file:
        path: "/etc/ci/mirror_info.sh"
        state: "touch"

    - name: Copy repos directory to opt workspace
      copy:
        src: /etc/yum.repos.d
        dest: /opt/
        remote_src: true
        mode: "0777"
