---
- name: Configure chrony service
  hosts: allovercloud
  become: true
  tasks:
    - name: Configure chrony
      import_role:
        name: chrony
        tasks_from: config.yml
      tags:
        - chrony
      when:
        - chrony_ntp_servers is defined
        - chrony_ntp_servers | length > 0
    - name: Run chrony
      import_role:
        name: chrony
        tasks_from: run.yml
      tags:
        - chrony
    - name: Run chrony (online)
      import_role:
        name: chrony
        tasks_from: online.yml
      tags:
        - chrony
    - name: Run chrony (sync)
      import_role:
        name: chrony
        tasks_from: sync.yml
      tags:
        - chrony
    - name: Run tripleo_timezone
      import_role:
        name: tripleo_timezone
        tasks_from: run.yml
      tags:
        - tripleo_timezone
