---
- name: Configure chrony service
  hosts: allovercloud
  become: true
  tasks:
    - name: Load chrony related vars
      import_role:
        name: chrony
      tags:
        - chrony
      when:
        - chrony_ntp_servers is defined
        - chrony_ntp_servers | length > 0
    - name: Run tripleo_timezone
      import_role:
        name: tripleo_timezone
      tags:
        - tripleo_timezone
