---
driver:
  name: podman

log: true

platforms:
  - name: ubi9
    hostname: ubi9
    image: ubi9/ubi-init
    registry:
      url: registry.access.redhat.com
    dockerfile: Dockerfile
    pkg_extras: python*setuptools
    volumes:
      - /etc/ci/mirror_info.sh:/etc/ci/mirror_info.sh:ro
      - /etc/pki/rpm-gpg:/etc/pki/rpm-gpg
      - /opt/yum.repos.d:/etc/yum.repos.d:rw
      - /etc/dnf/vars:/etc/dnf/vars
    privileged: true
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    ulimits: &ulimit
      - host

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          ubi9:
            ansible_python_interpreter: /usr/bin/python3
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - verify
    - destroy

verifier:
  name: testinfra
