---
driver:
  name: podman

provisioner:
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          centos:
            ansible_python_interpreter: /usr/bin/python3
        vars:
          # use a tmp hosts path since /etc/hosts isn't writeable in the
          # molecule test containers
          tripleo_hosts_entries_hosts_path: /tmp/hosts
          tripleo_hosts_entries_undercloud_hosts_entries: []
          tripleo_hosts_entries_extra_hosts_entries: []
          tripleo_hosts_entries_vip_hosts_entries: []
          tripleo_stack_name: overcloud
          plan: overcloud
          cloud_domain: localdomain
          enabled_networks:
            - ctlplane
            - InternalApi
          role_networks:
            - ctlplane
            - InternalApi
            - DisabledNet
          networks:
            ctlplane:
              name_lower: ctlplane
            InternalApi:
              name_lower: internal_api
        children:
          allovercloud:
            hosts:
              centos:
                hostname_resolve_network: ctlplane
                ctlplane_ip: 192.168.24.1
                internal_api_ip: 172.17.0.1

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - verify
    - destroy

verifier:
  name: ansible
