---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# "{{ role_name }}" will search for and load any operating system variable file
# found within the "vars/" path. If no OS files are found the task will skip.
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - skip: true
      files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_version'].split('.')[0] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
  tags:
    - always

- name: Detect mirrors file
  stat:
    path: "{{ test_deps_mirrors_file_path }}"
  register: mirrors_file

- name: RHEL Block
  become: true
  when:
    - (ansible_facts['os_family'] | lower) == 'redhat'
    - mirrors_file.stat.exists | bool
  block:
    - name: Fetch latest repo version
      uri:
        url: https://trunk.rdoproject.org/centos{{ ansible_facts['distribution_major_version'] }}-train/current/delorean.repo
        return_content: true
      register: tripleo_packages

    - name: Create default repo file
      copy:
        content: "{{ tripleo_packages.content }}"
        dest: /etc/yum.repos.d/delorean.repo
        mode: 0644

- name: Install tripleo-repos package
  become: true
  package:
    name: "python*-tripleo-repos"
    state: latest

- name: Tripleo setup block
  become: true
  when:
    - (ansible_facts['os_family'] | lower) == 'redhat'
    - test_deps_setup_tripleo | bool
  block:
    - name: Create tripleo repos
      command: tripleo-repos {{ test_deps_setup_stream | ternary('--stream', '--no-stream', omit) }} -b master current-tripleo

    - name: Install tripleo packages
      package:
        name: "{{ test_deps_tripleo_packages }}"
        state: present
        disable_gpg_check: true

- name: List configured repos
  become: true
  command: dnf repolist
  register: repo_list
  ignore_errors: true

- name: Print configured repos
  debug:
    msg: "{{ repo_list }}"

- name: Package block
  become: true
  block:
    - name: Install selinux python libs
      package:
        name: "{{ test_deps_selinux_packages }}"
        state: present
      when:
        - (ansible_facts['os_family'] | lower) == 'redhat'

    - name: Install extra packages
      package:
        name: "{{ test_deps_extra_packages }}"
        state: present
      when:
        - (test_deps_extra_packages | length) > 0
