---
- name: ensure rndc configuration path exists
  become: true
  file:
      path: "{{ designate_worker_config_file_path }}/private"
      state: directory

- name: create rndc configurations for each bind instance
  become: true
  template:
      src: rndc.conf.j2
      dest: "{{ designate_worker_config_file_path }}/private/bind{{ item.0|int + 1 }}.conf"
  with_indexed_items: "{{ designate_bind_node_ips  }}"
