---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# Assumes the following module is in ANSIBLE_LIBRARY=/usr/share/ansible/library/
#   https://github.com/ceph/ceph-ansible/blob/master/library/ceph_pool.py

- name: Get the current mon
  command: |
    {{ container_cli }} ps -a -f 'name=ceph-?(.*)-mon.*' --format \{\{\.Command\}\} --no-trunc
  register: ceph_mon
  become: true
  delegate_to: "{{ mon_instance }}"

- name: Check the resulting mon container instance
  set_fact:
    current_mon: "{{ ceph_mon.stdout | regex_replace('^-n mon.(.*)(?P<inst>) -f (.*)+$', '\\1') }}"

- name: Check the resulting mon container instance
  debug:
    msg: "{{ current_mon }}"
  when: tripleo_cephadm_verbose | bool

- name: insert new default crush rule into daemon to prevent restart
  become: true
  command: |
    {{ tripleo_cephadm_ceph_cli }} --admin-daemon /var/run/ceph/{{ tripleo_cephadm_cluster }}-mon.{{ current_mon }}.asok \
    config set osd_pool_default_crush_rule {{ info_ceph_default_crush_rule_yaml.rule_id }}
  changed_when: false
  delegate_to: "{{ mon_instance }}"
  when:
    - info_ceph_default_crush_rule_yaml | default('') | length > 0
