---
- name: Create a neutron port for a new address
  os_port:
    state: present
    network: "{{ network_name }}"
    fixed_ips:
      - subnet_id: "{{ subnet_id }}"
    no_security_groups: True
    name: "designate-{{ item }}-integration-port"
  register: _dns_designate_ports
  loop: "{{ hosts_for_ports }}"

- name: Record the new IP as a host fact
  set_fact:
    tripleo_dns_listen_interfaces: "[ '{{ item.port.fixed_ips[0].ip_address }}' ]"
  delegate_to: "{{ item.item }}"
  delegate_facts: true
  loop: "{{ _dns_designate_ports.results }}"

- name: Generate list of extra IPs for allow_notify
  set_fact:
    gather_tripleo_other_allow_notify: "{% for bind_node in (hosts_for_ports) %}{{ hostvars[bind_node].tripleo_dns_listen_interfaces[0] }}, {%endfor%}"

- name: distribute other host IPs for configuring allow lists
  set_fact:
    tripleo_other_allow_notify: "{{ gather_tripleo_other_allow_notify[:-2].split(',') | list }}"
  delegate_facts: true
  delegate_to: "{{ item }}"
  loop: "{{ hosts_for_ports }}"
